[project]
name = "lecture-07-bert-benchmarks"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "anthropic>=0.96.0",
    "arc-agi>=0.9.8",
    "arcengine>=0.9.3",
    "datasets>=4.8.4",
    "ipykernel>=7.2.0",
    "jupyter>=1.1.1",
    "jupyterlab>=4.5.6",
    "matplotlib>=3.10.8",
    "openai>=2.32.0",
    "pandas>=3.0.2",
    "torch>=2.11.0",
    "transformers>=5.5.4",
]
